### PR TITLE
Updated Heimdall version to 0.0.60

### PR DESCRIPTION
**Pull request by sundayScoop**
I couldn't build it to test myself as some npm packages such as https://npm.pkg.github.com/@amalsaju%2fbuttercup-server-client require privileged access.

I highly doubt anything will severely break, although if it doesn't work I think it would be best to help me build it myself so I can see what goes wrong.

### CODE REVIEW

**Comment by muddykat-tech** [comment]
That's fair, the issue with the package seems to be related to needing a GitHub Token that allows package downloads.

@amalsaju is in the process of fixing the reference to that package, and eventually it'll use the npm registry inplace of the github registry which will prevent this issue from occurring.

**Comment by amalsaju** [comment]
That's weird since it has been fixed. I removed the wrong version from github.

**Comment by amalsaju** [comment]
I did see that buttercup-core has the wrong version. Maybe that's the issue?

Also @muddykat-tech you need to remove the .npmrc file (or at least the one that redirects to my github), since buttercup-server-client is now hosted on npm.

**Comment by sundayScoop** [comment]
Just remembered! @muddykat-tech @amalsaju FieldData doesn't work with strings anymore, it works with Uint8Arrays. Same thing when you're decrypting, the .Data field will be an Uint8Array.

I did this so we work with the most primitive data type, ie bytes. Imagine someone wants to encrypt a photo, they would never encode it as a string, they would just have a byte array. So you'll also have to serialize/deserialize the data you encrypt/decrypt.

See the newest example here: https://github.com/tide-foundation/heimdall/blob/4cc6795d235dadd9e0cfaa0ec60cc5747184d602/example.html#L42

**Pull request merged**
